`SharedWaveformBaseline`: fix crash when no waveforms are signal-free
SBNSoftware/icarusalg pull request #86
Opened 2024-06-28 05:15 UTC by PetrilloAtWork

The `SharedWaveformBaseline` algorithm is run at `Stage0` to determine a baseline from all the PMT waveforms (this is the last change, since after `Stage0` the content of most of the waveforms is dropped).

This algorithm tries to be picky and to exclude waveforms which appear to have some signal in the region the baseline is going to be extracted from. As explained later, it is an extremely rare occurrence that no waveform in a channel is signal-free. In this case, the algorithm throws an exception:
```
    ---- StdException BEGIN
      An exception was thrown while processing module PMTWaveformBaselinesFromChannelData/pmtbaselines run: 11973 subRun: 1 event: 114516
      StatCollector<>::Average(): divide by 0
    ---- StdException END
```
This was first reported by @icaromx.

The proposed code uses a fall-back algorithm when there are no signal-free waveforms.
The fallback is not great, but after all it's a fallback: we take the maximum value of each waveform (assuming that the signal has negative polarity and that there is no significant undershoot after the signal), and take the median value among those.

Reviewers:
 * @mvicenzi who is informed on the algorithm, the context, the PMT, the DAQ and pretty much all the rest;
 * @SFBayLaser because he probably wants this fixed.

#### About the overestimation in the fall-back algorithm

The fallback algorithm will definitely overestimate the baseline (value higher than it should). There are possible mitigations to this as well: for example, we do have a (questionable) baseline RMS value, so we could subtract a number of RMS based on the statistics related to the maximum (e.g. if we have 9,997 samples and they are equally spaced in the cumulative distribution of a normal curve, the maximum value is 3 standard deviations above the mean, so we can subtract 3 RMS from it and call it a baseline).

In the end, I don't think the case is common enough to warrant more care than the one in this fix.

#### About the likelihood of this issue being triggered

Because of how the readout of ICARUS PMT is designed, the pre-trigger time of all waveforms is almost always signal-free; this does not hold for the waveforms acquired on the beam gate, though. In some very rare cases, there is no waveform acquired outside the beam gate, and for some channels it may happen that there is signal at the very beginning of the beam gate. I thought this case to be exceedingly rare, which is true, but I did not appreciate that when it happens my code ([`StatsCollector::Average()`](https://code-doc.larsoft.org/docs/latest/html/classlar_1_1util_1_1StatCollector.html#a799c5d81b7e11cc9fcc243ce1f5f625a), specifically) throws an exception rather than returning a `nan`.

2024-06-28 14:30 UTC, mvicenzi requested changes
Thanks for the quick patch @PetrilloAtWork !
I have only one question/concern on the fall-back method. 

Looking at the sample files provided by @icaromx, it seems the most common (only?) occurance is in fact cases when there is only *one* waveform available in the event. Given that scenario, the fallback method of taking the median of the maxima becomes just taking the maximum of that particular waveform. 

Looking at these waveforms, the "signal" in the pre-trigger region is tipically a sharp peak, so I feel taking the maximum would overstimate the baseline much more than needed. Taking the median of that single waveform would be much better. 
For cases with more than 1 waveform (not seen here), we can just take the mean of the medians.

Why are we not going for this solution? Are we afraid of large/long signals in the pre-trigger? (that doesn't seem the case from this sample events...)

2024-07-03 19:52 UTC, PetrilloAtWork commented
Adopted a solution of using the median of medians (for each waveform, the median sample is extracted from the whole waveform, then we take the median of the set of medians thus found).

2024-07-04 16:16 UTC, mvicenzi commented on icarusalg/PMT/Algorithms/SharedWaveformBaseline.cxx
> +    // backup: take the median of the maximum sample values on all waveforms
```suggestion
    // backup: take the median of the medians of all waveforms
```

2024-07-04 16:19 UTC, mvicenzi approved these changes
I agree with the changes! Just pointing out a small correction below, but I approve.

2024-07-05 23:04 UTC, PetrilloAtWork commented
Fixed via GitHub commit. Thank you for catching that.

2024-07-08 21:39 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00

2024-07-08 21:50 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23190&builds=)

2024-07-08 21:52 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23191&builds=)

2024-07-08 21:58 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10253&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10253&platform=Linux%20slf7&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23191&builds=)

2024-07-08 22:04 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10252&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10252&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23190&builds=)

2024-07-08 22:16 UTC, mmrosenberg commented
trigger build

2024-07-08 22:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23192&builds=)

2024-07-08 22:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23193&builds=)

2024-07-08 22:23 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10255&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10255&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23193&builds=)

2024-07-08 22:35 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10254&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10254&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23192&builds=)

2024-07-09 04:39 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbndaq-artdaq-core@v1_09_00of1 SBNSoftware/sbncode@v09_90_00 SBNSoftware/sbnanaobj@v09_23_00_01 SBNSoftware/sbnobj@v09_19_01

2024-07-09 04:51 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23196&builds=)

2024-07-09 16:57 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbndaq-artdaq-core@v1_09_00of1 SBNSoftware/sbncode@v09_90_00 SBNSoftware/sbnanaobj@v09_23_00_01 SBNSoftware/sbnobj@v09_19_01

2024-07-09 17:09 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23207&builds=)

2024-07-09 17:10 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23206&builds=)

2024-07-10 16:08 UTC, mmrosenberg commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbndaq-artdaq-core@v1_09_00of1 SBNSoftware/sbncode@v09_90_00 SBNSoftware/sbnanaobj@v09_23_00_01 SBNSoftware/sbnobj@v09_19_01

2024-07-10 16:22 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23216&builds=)

2024-07-10 16:24 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23217&builds=)

2024-07-10 16:31 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10271&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10271&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23217&builds=)

2024-07-10 16:47 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10270&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10270&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23216&builds=)

2024-07-18 15:28 UTC, mmrosenberg commented
trigger build

2024-07-18 15:31 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23298&builds=)

2024-07-18 15:31 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23297&builds=)

2024-07-18 15:34 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/10330&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/10330&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23298&builds=)

2024-07-18 16:21 UTC, merged